/**
 * Apache Fineract REST API
 * Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.
 *
 * The version of the OpenAPI document: 1.11.0-SNAPSHOT
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Fund } from './fund';
import { MonetaryCurrency } from './monetaryCurrency';
import { LoanProductGuaranteeDetails } from './loanProductGuaranteeDetails';
import { Rate } from './rate';
import { ExternalId } from './externalId';
import { LoanProductPaymentAllocationRule } from './loanProductPaymentAllocationRule';
import { Charge } from './charge';
import { LoanProductConfigurableAttributes } from './loanProductConfigurableAttributes';
import { DelinquencyBucket } from './delinquencyBucket';
import { LoanProductTrancheDetails } from './loanProductTrancheDetails';
import { LoanProductMinMaxConstraints } from './loanProductMinMaxConstraints';
import { Money } from './money';
import { LoanProductBorrowerCycleVariations } from './loanProductBorrowerCycleVariations';
import { LoanProductInterestRecalculationDetails } from './loanProductInterestRecalculationDetails';
import { LoanProductRelatedDetail } from './loanProductRelatedDetail';
import { LoanProductCreditAllocationRule } from './loanProductCreditAllocationRule';
import { LoanProductFloatingRates } from './loanProductFloatingRates';
import { LoanProductVariableInstallmentConfig } from './loanProductVariableInstallmentConfig';


export interface LoanProduct { 
    accountMovesOutOfNPAOnlyOnArrearsCompletion?: boolean;
    accountingDisabled?: boolean;
    accountingRule?: number;
    allowApprovedDisbursedAmountsOverApplied?: boolean;
    allowVariabeInstallments?: boolean;
    arrearsBasedOnOriginalSchedule?: boolean;
    borrowerCycleVariations?: Set<LoanProductBorrowerCycleVariations>;
    canDefineInstallmentAmount?: boolean;
    canUseForTopup?: boolean;
    cashBasedAccountingEnabled?: boolean;
    charges?: Array<Charge>;
    closeDate?: string;
    creditAllocationRules?: Array<LoanProductCreditAllocationRule>;
    currency?: MonetaryCurrency;
    delinquencyBucket?: DelinquencyBucket;
    description?: string;
    disallowExpectedDisbursements?: boolean;
    dueDaysForRepaymentEvent?: number;
    enableInstallmentLevelDelinquency?: boolean;
    equalAmortization?: boolean;
    externalId?: ExternalId;
    fixedPrincipalPercentagePerInstallment?: number;
    floatingRates?: LoanProductFloatingRates;
    fund?: Fund;
    holdGuaranteeFunds?: boolean;
    id?: number;
    includeInBorrowerCycle?: boolean;
    installmentAmountInMultiplesOf?: number;
    interestPeriodFrequencyType?: LoanProduct.InterestPeriodFrequencyTypeEnum;
    interestRecalculationEnabled?: boolean;
    linkedToFloatingInterestRate?: boolean;
    loanConfigurableAttributes?: LoanProductConfigurableAttributes;
    loanProductGuaranteeDetails?: LoanProductGuaranteeDetails;
    loanProductMinMaxConstraints?: LoanProductMinMaxConstraints;
    loanProductRelatedDetail?: LoanProductRelatedDetail;
    loanProductTrancheDetails?: LoanProductTrancheDetails;
    maxNominalInterestRatePerPeriod?: number;
    maxNumberOfRepayments?: number;
    maxPrincipalAmount?: Money;
    minNominalInterestRatePerPeriod?: number;
    minNumberOfRepayments?: number;
    minPrincipalAmount?: Money;
    minimumDaysBetweenDisbursalAndFirstRepayment?: number;
    multiDisburseLoan?: boolean;
    name?: string;
    _new?: boolean;
    nominalInterestRatePerPeriod?: number;
    numberOfRepayments?: number;
    overAppliedCalculationType?: string;
    overAppliedNumber?: number;
    overDueDaysForRepaymentEvent?: number;
    overdueDaysForNPA?: number;
    paymentAllocationRules?: Array<LoanProductPaymentAllocationRule>;
    periodicAccrualAccountingEnabled?: boolean;
    principalAmount?: Money;
    principalThresholdForLastInstallment?: number;
    productInterestRecalculationDetails?: LoanProductInterestRecalculationDetails;
    rates?: Array<Rate>;
    repaymentStartDateType?: LoanProduct.RepaymentStartDateTypeEnum;
    shortName?: string;
    startDate?: string;
    syncExpectedWithDisbursementDate?: boolean;
    transactionProcessingStrategyCode?: string;
    transactionProcessingStrategyName?: string;
    upfrontAccrualAccountingEnabled?: boolean;
    useBorrowerCycle?: boolean;
    variableInstallmentConfig?: LoanProductVariableInstallmentConfig;
}
export namespace LoanProduct {
    export type InterestPeriodFrequencyTypeEnum = 'DAYS' | 'WEEKS' | 'MONTHS' | 'YEARS' | 'WHOLE_TERM' | 'INVALID';
    export const InterestPeriodFrequencyTypeEnum = {
        Days: 'DAYS' as InterestPeriodFrequencyTypeEnum,
        Weeks: 'WEEKS' as InterestPeriodFrequencyTypeEnum,
        Months: 'MONTHS' as InterestPeriodFrequencyTypeEnum,
        Years: 'YEARS' as InterestPeriodFrequencyTypeEnum,
        WholeTerm: 'WHOLE_TERM' as InterestPeriodFrequencyTypeEnum,
        Invalid: 'INVALID' as InterestPeriodFrequencyTypeEnum
    };
    export type RepaymentStartDateTypeEnum = 'INVALID' | 'DISBURSEMENT_DATE' | 'SUBMITTED_ON_DATE';
    export const RepaymentStartDateTypeEnum = {
        Invalid: 'INVALID' as RepaymentStartDateTypeEnum,
        DisbursementDate: 'DISBURSEMENT_DATE' as RepaymentStartDateTypeEnum,
        SubmittedOnDate: 'SUBMITTED_ON_DATE' as RepaymentStartDateTypeEnum
    };
}


