/**
 * Apache Fineract REST API
 * Apache Fineract is a secure, multi-tenanted microfinance platform. The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The https://cui.fineract.dev[reference app] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation. Until we complete the new REST API documentation you still have the legacy documentation available https://fineract.apache.org/legacy-docs/apiLive.htm[here]. Please check https://fineract.apache.org/docs/current[the Fineract documentation] for more information.
 *
 * The version of the OpenAPI document: 1.11.0-SNAPSHOT
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanProductBorrowerCycleVariations { 
    borrowerCycleNumber?: number;
    defaultValue?: number;
    id?: number;
    maxValue?: number;
    minValue?: number;
    _new?: boolean;
    paramType?: LoanProductBorrowerCycleVariations.ParamTypeEnum;
    valueConditionType?: LoanProductBorrowerCycleVariations.ValueConditionTypeEnum;
}
export namespace LoanProductBorrowerCycleVariations {
    export type ParamTypeEnum = 'INVALID' | 'PRINCIPAL' | 'INTERESTRATE' | 'REPAYMENT';
    export const ParamTypeEnum = {
        Invalid: 'INVALID' as ParamTypeEnum,
        Principal: 'PRINCIPAL' as ParamTypeEnum,
        Interestrate: 'INTERESTRATE' as ParamTypeEnum,
        Repayment: 'REPAYMENT' as ParamTypeEnum
    };
    export type ValueConditionTypeEnum = 'INVALID' | 'EQUAL' | 'GREATERTHAN';
    export const ValueConditionTypeEnum = {
        Invalid: 'INVALID' as ValueConditionTypeEnum,
        Equal: 'EQUAL' as ValueConditionTypeEnum,
        Greaterthan: 'GREATERTHAN' as ValueConditionTypeEnum
    };
}


